---
- name: Create the address controller config map
  shell: oc create configmap address-controller-config --from-literal=enableRbac={{ enable_rbac }} --from-literal=environment={{ enmasse_environment }}
- name: Create the address space definitions
  shell: oc apply -f {{ playbook_dir }}/resources/address-controller/address-space-definitions.yaml
- name: Create the address controller deployment
  shell: oc apply -f {{ playbook_dir }}/resources/address-controller/deployment.yaml
