---
- name: Create EnMasse API Server Deployment
  shell: oc apply -n {{ namespace }} -f "{{ playbook_dir }}/resources/api-server/deployment.yaml"
- name: Create EnMasse API Server Service
  shell: oc apply -n {{ namespace }} -f "{{ playbook_dir }}/resources/api-server/service.yaml"
- name: Allow API Server to read Aggregation API client CA
  shell: oc adm policy add-cluster-role-to-user extension-apiserver-authentication-reader system:serviceaccount:{{ namespace }}:enmasse-admin
  when: secure_api_server
- name: Extract API Server CA
  shell: oc extract secret/api-server-cert -n {{ namespace }} --keys=tls.crt --to=-
  register: secret_result
- set_fact:
    ca_bundle: "{{ secret_result.stdout }}"
- name: Register API Server with API Aggregator
  when: register_api_server
  shell:
    cmd: |
      cat <<EOF | oc apply -f -
      apiVersion: apiregistration.k8s.io/v1beta1
      kind: APIService
      metadata:
        name: v1.enmasse.io
      spec:
        group: enmasse.io
        groupPriorityMinimum: 1000
        caBundle: "{{ ca_bundle | b64encode }}"
        version: v1
        versionPriority: 10
        service:
          name: api-server
          namespace: "{{ namespace }}"
      EOF
